### PR TITLE
Update for 1.3.0

### PR DESCRIPTION
**Pull request by muniategui**
This update tries to fix problems with the new update where some functions disappeared. It should work the disable mod and major relics should work (Agility and Astrology did not work properly)

Lesser Relics where not tested so they might not drop

### CODE REVIEW

**Comment by muniategui** [comment]
The mod was tested locally by removing TypeScript elements and making it raw JS since there are missing files for compilation. The Types were updated with official repository to the latest one

**Comment by sense-q** [comment]
It appears a lot of my mods broke with this update, I'm only now aware as I've been away from the scene. I'll be looking into the pr and whats changed in the game, thanks

**Comment by muniategui** [comment]
I have uploaded the mod in https://mod.io/g/melvoridle/m/armp1 with all the credits to you. If someone reports an error there, it is safe to assume that the error will be in the pr also. Thanks for your time and the mod <3!

**Comment by sense-q** [comment]
turns out not much was needed to change and didnt need to patch addprovidedstats, at least from what Ive been able to test. Thanks for getting a temporary fix out. Stats appear to apply correctly from what I can tell, please let me know if anything comes up. glhf!

**Pull request closed without merging**
